### 登录
POST http://localhost:3000/login
Content-Type: application/json

{"username":"admin","password":"123456"}

### 登出
POST http://localhost:3000/logout

### hello
GET http://localhost:3000/sysuser/hello
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImRhMmRiNmM3LWQxZDAtNDZmNi1hYWUyLTZhOTkzY2RiMjIxNSJ9.ZkjWoWnos5_aCIkcRAPhwUGOr8Bk24gmEsuWC6eBrxoFQZkL_7XjbFzV_ulTczZBlgZM-av-32l3o3R21jmHfw

### 获取用户信息
GET http://localhost:3000/sysuser?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImRhMmRiNmM3LWQxZDAtNDZmNi1hYWUyLTZhOTkzY2RiMjIxNSJ9.ZkjWoWnos5_aCIkcRAPhwUGOr8Bk24gmEsuWC6eBrxoFQZkL_7XjbFzV_ulTczZBlgZM-av-32l3o3R21jmHfw
